config/routes.rb
Crema::Application.routes.draw do

  get "welcome/home"
  resources :users

  resources :payments

  resources :enrolments

  resources :subjects

  resources :students

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  root 'welcome#home'

  

end

app/models/enrolment.rb
class Enrolment < ActiveRecord::Base
  belongs_to :student
  belongs_to :subject
end

app/controllers/enrolments_controller.rb
class EnrolmentsController < ApplicationController
  before_action :set_enrolment, only: [:show, :edit, :update, :destroy]

  # GET /enrolments
  # GET /enrolments.json
  def index
    @enrolments = Enrolment.all
  end

  # GET /enrolments/1
  # GET /enrolments/1.json
  def show
  end

  # GET /enrolments/new
  def new
    @enrolment = Enrolment.new
  end

  # GET /enrolments/1/edit
  def edit
  end

  # POST /enrolments
  # POST /enrolments.json
  def create
    @enrolment = Enrolment.new(enrolment_params)

    respond_to do |format|
      if @enrolment.save
        format.html { redirect_to @enrolment, notice: 'Enrolment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @enrolment }
      else
        format.html { render action: 'new' }
        format.json { render json: @enrolment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrolments/1
  # PATCH/PUT /enrolments/1.json
  def update
    respond_to do |format|
      if @enrolment.update(enrolment_params)
        format.html { redirect_to @enrolment, notice: 'Enrolment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @enrolment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrolments/1
  # DELETE /enrolments/1.json
  def destroy
    @enrolment.destroy
    respond_to do |format|
      format.html { redirect_to enrolments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrolment
      @enrolment = Enrolment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrolment_params
      params.require(:enrolment).permit(:student_id, :subject_id)
    end
end

app/helpers/enrolments_helper.rb
module EnrolmentsHelper
end

app/views/enrolments/_form.html.erb
<%= form_for(@enrolment) do |f| %>
  <% if @enrolment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrolment.errors.count, "error") %> prohibited this enrolment from being saved:</h2>

      <ul>
      <% @enrolment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student %><br>
    <%= f.text_field :student %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enrolments/edit.html.erb
<h1>Editing enrolment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrolment %> |
<%= link_to 'Back', enrolments_path %>

app/views/enrolments/index.html.erb
<h1>Listing enrolments</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Subject</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @enrolments.each do |enrolment| %>
      <tr>
        <td><%= enrolment.student %></td>
        <td><%= enrolment.subject %></td>
        <td><%= link_to 'Show', enrolment %></td>
        <td><%= link_to 'Edit', edit_enrolment_path(enrolment) %></td>
        <td><%= link_to 'Destroy', enrolment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrolment', new_enrolment_path %>

app/views/enrolments/new.html.erb
<h1>New enrolment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrolments_path %>

app/views/enrolments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @enrolment.student %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @enrolment.subject %>
</p>

<%= link_to 'Edit', edit_enrolment_path(@enrolment) %> |
<%= link_to 'Back', enrolments_path %>