config/routes.rb
Crema::Application.routes.draw do

  get "welcome/home"
  resources :users

  resources :payments

  resources :enrolments

  resources :subjects

  resources :students

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  root 'welcome#home'

  

end

app/models/student.rb
class Student < ActiveRecord::Base
	validates :name, presence: true
	validates :registration_number, uniqueness: true
	validates :email, presence: true
	validates :mobile, presence: true
	validates :school, presence: true

	has_many :enrolments
	has_many :payments
	has_many :subjects, :through => :enrolments

	def tuition_fee
		subjects.collect { |subject| subject.fee }.sum
	end

	def generate_registration_number
		"PLN-%.6d" % (id + 1)
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :signed_in_user
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @subjects = Subject.all
    # generate registration number based on last student id, if it is the first ever student, "PLN-000001"
    if Student.any? 
      @registration_number = Student.last.generate_registration_number
    else
      @registration_number = "PLN-000001"
    end
  end

  # GET /students/1/edit
  def edit
    @subjects = Subject.all
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)


    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        # when student creation fail validation, creation action render new action,
        # problem is, "create" don't have @subjects = Subject.all, "each" in view will
        # fail nil class error
        @subjects = Subject.all 
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :registration_number, :email, :mobile, :school, :tuition_fee, :subject_ids => [])
    end
end

app/helpers/students_helper.rb
module StudentsHelper


end

app/views/students/_form.html.erb
<%= form_for @student, :html => { class: "form-horizontal", role: "form" } do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-3"><%= f.text_field :name, :class => 'form-control' %></div>
  </div>
  <div class="form-group">
    <%= f.label :registration_number, class: 'col-sm-2 control-label' %>
    <% if @student.id %>
    <%= @student.registration_number %>
    <% else %>
    <div class="col-sm-3"><%= f.text_field :registration_number, :value => @registration_number, :class => 'form-control' %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-3"><%= f.text_field :email, :class => 'form-control' %></div>
  </div>
  <div class="form-group">
    <%= f.label :mobile, class: 'col-sm-2 control-label' %>
    <div class="col-sm-3"><%= f.text_field :mobile, :class => 'form-control' %></div>
  </div>
  <div class="form-group">
    <%= f.label :school, class: 'col-sm-2 control-label' %>
    <div class="col-sm-3"><%= f.text_field :school, :class => 'form-control' %></div>
  </div>
  

  <div class="form-group">
    <%= f.label :subject, class: 'checkbox col-sm-2 control-label'%>
    <div class="col-sm-3">
          <% @subjects.each do |subject| %>
            <li><%= check_box_tag :subject_ids, subject.id, @student.subjects.include?(subject), :class=> 'col-sm-3', :type => 'checkbox',:name => 'student[subject_ids][]' %><%= subject.name %></li>
          <% end %>
    </div>
  </div>


  <% if @subjects.blank? %>
    <p>There are no subjects in the record, create one?</p>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-3">
      <%= f.submit "Create Student", :class => "btn btn-large btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h3>All students</h3>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Registration Number</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>School</th>
      <th>Subjects taken</th>
      <th>Tuition fee</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.registration_number %></td>
        <td><%= student.email %></td>
        <td><%= student.mobile %></td>
        <td><%= student.school %></td>
        <td><% student.subjects.each do |subject| %>
              <li><%= subject.name %></li>
            <% end %>
        </td>
        <td><%= ringgit(student.tuition_fee) %>
          <span class="payment-toggle glyphicon glyphicon-plus-sign"></span>
            <div class="payment-details" style="display:none">
              <li><%= link_to 'Make Payment', new_payment_path(:student_id => student) %></li>
              <% unless student.payments.empty? %>
                <li>Last paid <%= Date::MONTHNAMES[(student.payments.last.paid_for_month).to_i] %>, <%= ringgit(student.payments.last.amount) %> </li>
              <% end %>
            </div>
        </td>
        
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Student', new_student_path, :class => "btn btn-primary btn-large" %>

app/views/students/new.html.erb
<h3>Create new student</h3>

<%= render 'form' %>

app/views/students/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Registration Number:</strong>
  <%= @student.registration_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @student.mobile %>
</p>

<p>
  <strong>School:</strong>
  <%= @student.school %>
</p>
<p>
  <strong>Subjects taken:</strong>
  <% @student.subjects.each do |subject| %>
    <%= subject.name %>
  <% end %>
</p>

<p>
  <strong>Tuition fee:</strong>
  <%= @student.tuition_fee %>
</p>
<h1>Payment History</h1>
<% @student.payments.each do |payment| %>
  <%= payment.created_at %>
  <%= payment.paid_for_month %>
  <%= payment.amount %>
<% end %>

<%= link_to 'Making Payment', new_payment_path(:student_id => @student) %>
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>