config/routes.rb
Crema::Application.routes.draw do

  get "welcome/home"
  resources :users

  resources :payments

  resources :enrolments

  resources :subjects

  resources :students

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  root 'welcome#home'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="#">Tutr apps</a>, by <a href="#">doppio</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "Contact", "#" %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
    		<%= link_to "Tutr", root_path, id: "logo" %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <% if signed_in? %>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Students", students_path %></li>
              <li><%= link_to "Subjects", subjects_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user)%></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path,  method: "delete" %>
                  </li>
                </ul>
              </li>
            <% end %>
        </ul>
      </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crema | <%= yield(:title) %> </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700|Open+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %> 
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
	  <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  

</body>
</html>